# EXAMPLE: deploy the Actual Budget sync server to fly.io.

app = '<your-actual-server>'
primary_region = '<your-region>'

[experimental]
  cmd = ['node', '--max-old-space-size=180', 'app.js']
  auto_rollback = true

[build]
  image = 'actualbudget/actual-server:latest'

[env]
  PORT = '5006'
  TINI_SUBREAPER = '1'

[[mounts]]
  source = 'actual_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 5006

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'
